project:
  type: website

website:
  title: "Victoria Peechatt"
  favicon: images/parasitoid_square.png
  bread-crumbs: true
  back-to-top-navigation: true
  navbar:
    left:
      - href: research.qmd
        text: Research
      - href: outreach.qmd
        text: Outreach & Activism
      - href: teaching.qmd
        text: Teaching & Mentorship
      - href: about.qmd
        text: About me & CV
      - href: acknowledgements.qmd
        text: Acknowledgements
  page-footer: 
    left: "Updated 2025-07-05, Victoria Peechatt" 
    right: "Made with Quarto"
    border: false

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true



