project:
  type: website

website:
  title: "Victoria Peechatt"
  image: images/buckeyelong.png
  bread-crumbs: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: outreach.qmd
        text: Outreach
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



